#!/usr/bin/env python

# Usage: msp430-txt-merge device.txt boot.txt

import sys
import re
import os

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print 'Usage:'
        print '  msp430-txt-merge main.txt boot.txt'
        sys.exit(1)

    da = os.path.dirname(sys.argv[1])
    db = os.path.dirname(sys.argv[2])
    na = os.path.basename(sys.argv[1])
    nb = os.path.basename(sys.argv[2])
    fc = open('%s%s%s-%s.txt' % (da,os.sep,na[0:-4],nb[0:-4]), 'w')

    fa = open(sys.argv[1], 'r')
    for la in fa:
        if re.match(r'^@10000', la):
            break
        else:
            #print la,
            fc.write(la)
    fa.close()

    fb = open(sys.argv[2], 'r')
    for lb in fb:
        if re.match(r'^q', lb):
            break
        else:
            #print lb,
            fc.write(lb)
    fb.close()

    fa = open(sys.argv[1], 'r')
    found = False
    for la in fa:
        if found:
            #print la,
            fc.write(la)
        else:
            if re.match(r'^@10000', la):
                found = True
                #print la,
                fc.write(la)
    fa.close()

    fc.close()
